import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Building2, Check, ChevronRight, ClipboardCheck, Leaf, Mail, Menu, Phone, ShieldCheck, TreePine, Users, X } from "lucide-react";

type Page = "home" | "servicos" | "florestas" | "fogo" | "clientes" | "sobre" | "contato";
const pageFromHash = (): Page => { const value = window.location.hash.replace("#", ""); return ["servicos", "florestas", "fogo", "clientes", "sobre", "contato"].includes(value) ? value as Page : "home"; };
const navItems: { label: string; page: Page }[] = [{ label: "Início", page: "home" }, { label: "Serviços", page: "servicos" }, { label: "Florestas plantadas", page: "florestas" }, { label: "PMIF / PPCIF", page: "fogo" }, { label: "Clientes", page: "clientes" }, { label: "Sobre a Reflora", page: "sobre" }];
const services = [
  { icon: TreePine, title: "Avaliação de risco de árvores", text: "Diagnósticos visuais e técnicos para orientar decisões e proteger pessoas, estruturas e patrimônio." },
  { icon: Leaf, title: "Gestão de áreas verdes", text: "Planejamento, inventário e acompanhamento para espaços urbanos, propriedades e áreas naturais." },
  { icon: ClipboardCheck, title: "Licenciamento ambiental", text: "Apoio técnico para projetos que precisam de conformidade, clareza e responsabilidade ambiental." },
  { icon: ShieldCheck, title: "Prevenção de incêndios", text: "Estratégias de prevenção e manejo para reduzir vulnerabilidades em áreas rurais e florestais." },
];
const clients = [
  { icon: Building2, title: "Órgãos públicos", text: "Prefeituras, secretarias, parques e gestores de vias públicas e áreas verdes.", tag: "Setor público" },
  { icon: BarChart3, title: "Empresas e concessionárias", text: "Indústrias, empresas e operações que precisam reduzir riscos e cuidar do território.", tag: "Corporativo" },
  { icon: Users, title: "Instituições e propriedades", text: "Condomínios, fazendas, escolas e propriedades particulares.", tag: "Particular" },
];
const portfolioItems = [
  { title: "Implantação de reflorestamento", text: "Planejamento, implantação e acompanhamento de projetos de recomposição e restauração ambiental." },
  { title: "Serviços em árvores urbanas", text: "Avaliação de risco, manejo, laudos e orientações para arborização em vias públicas, parques, escolas e propriedades." },
  { title: "Licenciamento ambiental", text: "Apoio técnico para organizar estudos, documentos e processos junto aos órgãos ambientais." },
  { title: "Consultoria estratégica", text: "Consultoria sob medida para antecipar riscos, orientar decisões e dar clareza às exigências ambientais de cada projeto." },
];
const fireServices = [
  ["Mapeamento e risco", "Classificação por combustível vegetal e vulnerabilidade ambiental."],
  ["Medidas preventivas", "Planejamento e implementação de aceiros adequados."],
  ["Monitoramento avançado", "FMA+, satélite e rondas para cálculo contínuo do perigo."],
  ["Brigadas e resposta", "Dimensionamento, capacitação e planos de emergência."],
  ["Gestão digital", "Dados e mapeamentos para apoiar equipes e decisões."],
  ["Conscientização", "Campanhas de educação ambiental e sinalização preventiva."],
];
const forestProducts = [
  { category: "Herbicidas", products: "Touchdown e Sequence", text: "Soluções para dessecação e controle de plantas daninhas na linha e entrelinha de plantações de eucalipto e pinus." },
  { category: "Fungicidas", products: "Priori Top e Priori Xtra", text: "Proteção preventiva e curativa para doenças como ferrugem e oídio em cultivos de eucalipto." },
  { category: "Inseticidas", products: "Actara e Match", text: "Manejo de pragas como cupins, vespa-da-galha e lagartas, com orientação conforme cultura, dose e modalidade." },
  { category: "Adjuvantes", products: "Agral e Ochima", text: "Produtos que ajudam no espalhamento, na distribuição e na absorção das caldas aplicadas." },
  { category: "Bioestimulante", products: "Quantis", text: "Fertilizante líquido orgânico para aplicações foliares, enraizamento, estabelecimento e redução de estresses." },
  { category: "Indutor de resistência", products: "Bion 500 WG", text: "Ativador preventivo dos mecanismos naturais de defesa das plantas contra doenças bacterianas." },
];
function goTo(page: Page) { window.location.hash = page === "home" ? "" : page; window.scrollTo({ top: 0, behavior: "smooth" }); }
function Header({ page }: { page: Page }) { const [open, setOpen] = useState(false); return <header className="site-header"><button className="brand" onClick={() => goTo("home")} aria-label="Ir para o início"><span>REFLORA<span className="accent">.</span></span><small>Serviços florestais e ambientais</small></button><nav className={open ? "main-nav is-open" : "main-nav"}>{navItems.map((item) => <button key={item.page} className={page === item.page ? "active" : ""} onClick={() => { goTo(item.page); setOpen(false); }}>{item.label}</button>)}<button className="header-cta" onClick={() => { goTo("contato"); setOpen(false); }}><Phone size={16} /> Fale conosco</button></nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Abrir menu">{open ? <X /> : <Menu />}</button></header>; }
function Button({ children, onClick, secondary = false }: { children: React.ReactNode; onClick: () => void; secondary?: boolean }) { return <button className={secondary ? "button button-secondary" : "button"} onClick={onClick}>{children}<ArrowRight size={17} /></button>; }
function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="page-intro"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>; }
function ServiceCard({ icon: Icon, title, text }: typeof services[number]) { return <article className="service-card"><div className="icon-box"><Icon size={22} /></div><h3>{title}</h3><p>{text}</p><span className="card-arrow"><ArrowRight size={18} /></span></article>; }
function Home() { return <><section className="hero"><div className="hero-image" /><div className="hero-content"><span className="eyebrow light">Serviços florestais e ambientais</span><h1>Decisões mais seguras para árvores e territórios.</h1><p>A Reflora transforma análise técnica em cuidado prático para pessoas, patrimônios e meio ambiente.</p><div className="hero-actions"><Button onClick={() => goTo("servicos")}>Conheça nossos serviços</Button><Button secondary onClick={() => goTo("contato")}>Fale com a equipe</Button></div></div><div className="hero-note"><span>01</span><p>Avaliação técnica<br /><strong>para agir com clareza.</strong></p></div></section><section className="quick-section"><div className="section-heading"><div><span className="eyebrow">Visão geral</span><h2>O essencial para começar.</h2></div><button className="text-link" onClick={() => goTo("sobre")}>Conheça a Reflora <ChevronRight size={16} /></button></div><div className="quick-grid"><article className="feature-panel"><div className="feature-number">01</div><h3>Diagnóstico antes da decisão</h3><p>Observamos cada contexto para identificar riscos, prioridades e caminhos de manejo.</p><Button onClick={() => goTo("servicos")}>Ver serviços</Button></article><div className="stat-list"><div><strong>5 etapas</strong><span>do diagnóstico à orientação</span></div><div><strong>3 públicos</strong><span>atendidos pela nossa equipe</span></div><div><strong>1 propósito</strong><span>cuidar com responsabilidade</span></div></div></div></section><section className="service-preview"><div className="section-heading"><div><span className="eyebrow">Atuação</span><h2>Onde podemos ajudar.</h2></div><button className="text-link" onClick={() => goTo("servicos")}>Todos os serviços <ChevronRight size={16} /></button></div><div className="service-grid">{services.slice(0, 3).map((service) => <ServiceCard key={service.title} {...service} />)}</div></section><section className="home-callout"><div><span className="eyebrow light">Próximo passo</span><h2>Tem uma área que precisa de atenção?</h2><p>Conte um pouco sobre o seu desafio. A equipe Reflora ajuda a encontrar o escopo certo.</p></div><Button onClick={() => goTo("contato")}>Iniciar conversa</Button></section></>; }
function Services() { return <><PageIntro eyebrow="O que fazemos" title="Conhecimento técnico que vira ação." text="Unimos conhecimento técnico, planejamento e execução para transformar desafios ambientais em decisões mais seguras e responsáveis." /><section className="content-section"><div className="service-grid full">{services.map((service) => <ServiceCard key={service.title} {...service} />)}</div><div className="method"><div><span className="eyebrow">Nossa forma de trabalhar</span><h2>Do diagnóstico à decisão.</h2><p className="section-copy">Cada projeto começa com uma leitura precisa das condições ambientais, dos riscos e das necessidades específicas da área.</p></div><div className="method-steps">{["Levantamento das condições, riscos e necessidades", "Estruturação de projetos, documentos e prioridades", "Execução, monitoramento e avaliação dos resultados"].map((step, index) => <div key={step}><strong>0{index + 1}</strong><span>{step}</span></div>)}</div></div><div className="subsection"><span className="eyebrow">Portfólio Reflora</span><h2>Soluções para cada etapa do projeto florestal.</h2><p className="section-copy">Da implantação ao acompanhamento, integramos planejamento ambiental, gestão florestal e análise econômica para apoiar decisões mais sustentáveis.</p><div className="portfolio-grid">{portfolioItems.map((item) => <article key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section><section className="fire-section"><div><span className="eyebrow light">Gestão do fogo</span><h2>Prevenção baseada em diagnóstico e resposta.</h2><p>A Reflora desenvolve e executa projetos especializados em Plano de Manejo Integrado do Fogo (PMIF) e Plano de Prevenção e Combate a Incêndios Florestais (PPCIF), atendendo aos requisitos da Lei Federal nº 14.944/2024, do Código Florestal e da Lei de Crimes Ambientais.</p><p>Nossa equipe técnica é liderada pelos Engenheiros Florestais Marco Aurélio Busch Ziliotto, CREA 23402/D, e Sergio Dyminski Arruda, CREA-PR 25835/D.</p></div><div className="pill-grid">{fireServices.map(([title, text]) => <article key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></section></>; }
function Forests() { return <><PageIntro eyebrow="Florestas plantadas" title="Soluções completas para eucalipto e pinus." text="A Reflora apoia todas as etapas dos cultivos florestais, do planejamento e implantação ao manejo, monitoramento e planejamento da produção." /><section className="content-section"><div className="document-intro"><span className="eyebrow">Portfólio técnico</span><h2>Conheça as frentes de cuidado para sua floresta.</h2><p className="section-copy">O portfólio apresentado nos documentos reúne herbicidas, fungicidas, inseticidas, adjuvantes, bioestimulantes e indutores de resistência. A recomendação deve considerar cultura, modalidade, dose, modo de uso e as exigências do rótulo e da bula.</p></div><div className="forest-grid">{forestProducts.map((item) => <article key={item.category}><span className="eyebrow">{item.category}</span><h2>{item.products}</h2><p>{item.text}</p></article>)}</div><div className="notice-panel"><h2>Uso responsável e orientação técnica.</h2><p>Consulte sempre um engenheiro agrônomo. Produto de uso agrícola, com venda sob receituário agronômico. Utilize equipamentos de proteção individual, aplique somente as doses recomendadas e descarte corretamente embalagens e restos de produtos.</p><p>As informações de classificação toxicológica e de periculosidade ambiental devem ser verificadas no rótulo, na bula e na receita do produto. Para restrições de uso em determinados Estados, consulte a bula.</p></div></section></>; }
function FirePlans() { return <><PageIntro eyebrow="PMIF e PPCIF" title="Planejamento para prevenir e responder aos incêndios florestais." text="A Reflora possui conhecimento e experiência para realizar o Plano de Manejo Integrado do Fogo e o Plano de Prevenção e Combate a Incêndios Florestais." /><section className="content-section"><div className="fire-overview"><div><span className="eyebrow">Legislação aplicada</span><h2>Lei nº 14.944, de 31 de julho de 2024.</h2><p className="section-copy">A Política Nacional de Manejo Integrado do Fogo define o PMIF e suas etapas, além de regular queimas prescritas e queimas controladas, em conjunto com o Código Florestal e a Lei de Crimes Ambientais.</p></div><div className="credentials"><strong>Responsáveis técnicos</strong><span>Eng. Florestal Sergio Dyminski Arruda<br />CREA-PR 25835/D</span><span>Eng. Florestal Marco Aurélio Busch Ziliotto<br />CREA 23402/D</span></div></div><div className="subsection"><span className="eyebrow">Etapas do PMIF</span><h2>Da leitura do território às metas.</h2><div className="plan-steps">{["Diagnóstico ambiental", "Objetivos e diretrizes", "Mapeamento de risco", "Manejo do fogo", "Estratégias de prevenção"].map((step, index) => <article key={step}><strong>0{index + 1}</strong><h3>{step}</h3></article>)}</div></div><div className="risk-method"><span className="eyebrow">Método DYMINSKI</span><h2>Potencial de risco, severidade e frequência.</h2><p className="section-copy">O potencial de risco é avaliado a partir do tipo de uso e ocupação do solo, da presença de combustível vegetal e do fator humano. A matriz combinada cruza gravidade ou severidade com probabilidade ou frequência para identificar pontos de atenção, também chamados de hotspots.</p><div className="risk-levels"><span>Muito baixo</span><span>Baixo</span><span>Médio</span><span>Alto</span><span>Crítico</span></div></div><div className="prevention-list"><span className="eyebrow">Estratégias de prevenção</span><h2>Ações recomendadas pelo PMIF / PPCIF.</h2>{["Aceiros e faixas de domínio", "Campanhas, educação e materiais", "Monitoramento, ronda, satélite, FMA+, grau de perigo, sinalização e alertas", "Brigada florestal, capacitação, recursos e ajustes documentais", "Metas, avaliação de resultados e planos de resposta"].map((item, index) => <div key={item}><strong>{index + 1}</strong><span>{item}</span></div>)}</div><div className="notice-panel"><h2>Mapas e dados para a gestão direta.</h2><p>As considerações gerais, estratégias e metas são estruturadas com base nos dados gerados pelo mapeamento do potencial e do nível de risco. Os mapas digitais entregues fazem parte da ferramenta de gestão das ações do PMIF e PPCIF.</p></div></section></>; }
function Clients() { return <><PageIntro eyebrow="Clientes e parceiros" title="Uma solução para cada realidade ambiental." text="Atendemos organizações que precisam de diagnóstico técnico, planejamento ambiental e apoio para tomar decisões com mais segurança e conformidade." /><section className="content-section"><div className="client-grid">{clients.map(({ icon: Icon, ...client }) => <article className="client-card" key={client.title}><span className="client-tag">{client.tag}</span><Icon size={30} /><h2>{client.title}</h2><p>{client.text}</p><button className="text-link" onClick={() => goTo("contato")}>Conversar sobre um projeto <ChevronRight size={16} /></button></article>)}</div><div className="audience-grid"><article><span className="eyebrow">Setor público</span><h2>Gestão da arborização urbana também é gestão de segurança.</h2><p>A avaliação técnica auxilia gestores públicos no planejamento e na segurança de prefeituras, parques e vias públicas. Mais informação para melhores decisões.</p></article><article><span className="eyebrow">Setor privado</span><h2>Sua propriedade também precisa de uma avaliação.</h2><p>Identificamos riscos em condomínios, empresas e fazendas para ajudar a proteger pessoas e patrimônio.</p></article><article><span className="eyebrow">Escolas</span><h2>Em uma escola, prevenção não pode esperar.</h2><p>A circulação constante de crianças exige monitoramento preventivo rigoroso, registro técnico e acompanhamento periódico.</p></article></div></section></>; }
function About() { return <><PageIntro eyebrow="Sobre a Reflora" title="Conhecimento técnico para cuidar do território." text="A Reflora Serviços Ambientais desenvolve projetos e consultorias para unir conservação, segurança e viabilidade. Nossa atuação conecta o campo, a análise técnica e a tomada de decisão." /><section className="about-section"><div className="about-image" /><div className="about-copy"><span className="eyebrow">Nossa forma de trabalhar</span><h2>Clareza para quem precisa agir.</h2><p>Em cada projeto, olhamos para a árvore, a área e o entorno. O resultado é uma recomendação compreensível, tecnicamente responsável e conectada à realidade de quem vai colocá-la em prática.</p><ul>{["Diagnóstico: leitura precisa das condições ambientais", "Estratégia: planos claros para cada necessidade", "Responsabilidade: execução com segurança e conformidade"].map((item) => <li key={item}><Check size={18} />{item}</li>)}</ul><Button onClick={() => goTo("contato")}>Conhecer nosso trabalho</Button></div></section><section className="content-section"><div className="risk-intro"><span className="eyebrow">Método Reflora</span><h2>Uma avaliação que considera o contexto.</h2><p className="section-copy">Uma árvore saudável não é necessariamente uma árvore segura. A condição e a estrutura precisam ser analisadas junto da localização, exposição, circulação, ocupação, estruturas e bens ao redor.</p></div><div className="scenario-grid">{[["Cenário 01", "Árvore em área isolada, sem trânsito constante."], ["Cenário 02", "Árvore próxima a uma residência ou estrutura."], ["Cenário 03", "Árvore em área de grande circulação de pessoas."]].map(([title, text]) => <article key={title}><span>{title}</span><p>{text}</p></article>)}</div><div className="report-panel"><div><span className="eyebrow">Resultado da avaliação</span><h2>Registro técnico para a tomada de decisão.</h2><p className="section-copy">Cada árvore avaliada gera um registro técnico detalhado, organizando informações cruciais para planejar medidas, monitoramento e prioridades.</p></div><strong>ÁRVORE #024</strong></div></section></>; }
function Contact() { return <><PageIntro eyebrow="Contato" title="Vamos entender o seu desafio." text="Envie uma mensagem ou fale diretamente com a equipe Reflora. O primeiro passo é uma boa conversa." /><section className="contact-section"><div className="contact-info"><span className="eyebrow light">Canais diretos</span><h2>Estamos por perto.</h2><a href="tel:+5541999917280"><Phone size={19} />(41) 99991-7280</a><a href="mailto:contato@reflora.eco.br"><Mail size={19} />contato@reflora.eco.br</a><p>Atendimento para projetos públicos, corporativos e particulares.</p></div><form className="contact-form" onSubmit={(event) => event.preventDefault()}><label>Seu nome<input required placeholder="Como podemos chamar você?" /></label><label>E-mail ou telefone<input required placeholder="Para retornarmos o contato" /></label><label>Conte sobre o projeto<textarea required rows={4} placeholder="Área, cidade e o que você precisa avaliar" /></label><button className="button" type="submit">Enviar mensagem <ArrowRight size={17} /></button></form></section></>; }
export default function App() { const [page, setPage] = useState<Page>(pageFromHash); useEffect(() => { const update = () => setPage(pageFromHash()); window.addEventListener("hashchange", update); return () => window.removeEventListener("hashchange", update); }, []); const content = page === "home" ? <Home /> : page === "servicos" ? <Services /> : page === "florestas" ? <Forests /> : page === "fogo" ? <FirePlans /> : page === "clientes" ? <Clients /> : page === "sobre" ? <About /> : <Contact />; return <><Header page={page} /><main>{content}</main><footer><button className="brand footer-brand" onClick={() => goTo("home")}>REFLORA<span className="accent">.</span></button><span>Serviços florestais e ambientais</span><span>© 2026 Reflora</span></footer></>; }